### ISSUE TITLE
**maptools** retiring soon.

### ISSUE THREAD

**Issue by rsbivand** [guypwhunt/GEOexplorer#44]
I suggest that you plan to replace your call to  `"maptools::pointLabel"` at your earliest convenience, as the **maptools** package will  be archived soon. https://github.com/r-spatial/evolution/issues/5.

**Comment by rsbivand** [comment]
The `maptools::pointLabel` function is deprecated, and is now `car::pointLabel`.

**Comment by rsbivand** [comment]
CMD check with `sp` evolution status `2L` and current CRAN `maptools`:
[00check.log](https://github.com/guypwhunt/GEOexplorer/files/11627043/00check.log)
This version of `sp` will be submitted to CRAN June 10.

**Comment by guypwhunt** [comment]
Thanks, I have now removed Maptools from GEOexplorer

**Comment by rsbivand** [comment]
Note that the package (main HEAD) fails CMD check with `_R_CHECK_SUGGESTS_ONLY_=true` and forthcoming `sp` 2.0-0 with: 
[00check.log](https://github.com/guypwhunt/GEOexplorer/files/11706923/00check.log) even after adding `car` to Imports: in `DESCRIPTION`.

**Comment by rsbivand** [comment]
@guypwhunt Less than three weeks remain to fix this.
