### ISSUE TITLE
maptools should not be used

### ISSUE THREAD

**Issue by rsbivand** [guypwhunt/GEOexplorer#47]
Maptools (and rgdal and rgeos) are retiring in October. See https://r-spatial.org/r/2023/05/15/evolution4.html and earlier information for details. I'm now seeing:
[00check.log](https://github.com/guypwhunt/GEOexplorer/files/11516075/00check.log)
when testing with sp from https://github.com/rsbivand/sp/tree/sp161 and current maptools trunk from https://r-forge.r-project.org/R/?group_id=943, rev. 417. Failures in tests: 
[testthat.Rout.zip](https://github.com/guypwhunt/GEOexplorer/files/11516138/testthat.Rout.zip)
I note that you `importFrom(maptools,pointLabel)` - this function is in `car`.

**Comment by guypwhunt** [comment]
Thanks, I have now removed Maptools from GEOexplorer
